plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    -   - '@semantic-release/changelog'
        -   changelogFile: 'CHANGELOG.md'
    -   - '@semantic-release/github'
        -   assets:
                - 'CHANGELOG.md'
            publish: true
            message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
branches:
    - master
    -   name: development
        prerelease: true
